Erp/Portal/Areas/BaseData/Controllers/CustomerExecuteController.cs
using CommonService.Common;
using Context;
using Maticsoft.Common;
using Portal.Controllers;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portal.Areas.BaseData.Controllers
{
    /// <summary>
    /// 客户生命周期控制器
    /// </summary>
    public class CustomerExecuteController : BaseController
    {
        private readonly ICommonService.IC_Customer _customerWCF;
        private readonly ICommonService.FlowManager.IP_Business_flow _bussinessFlowWCF;
        private readonly ICommonService.SysManager.IC_Userinfo _userinfoWCF;
        private readonly ICommonService.SysManager.IC_Role_Role_Power _roleRolePowerWCF;
        private readonly ICommonService.IC_Parameters _parameterWCF;

        public CustomerExecuteController()
        {
            //服务初始化话
            _customerWCF = ServiceProxyFactory.Create<ICommonService.IC_Customer>("CustomerWCF");
            _bussinessFlowWCF = ServiceProxyFactory.Create<ICommonService.FlowManager.IP_Business_flow>("Business_flowWCF");
            _userinfoWCF = ServiceProxyFactory.Create<ICommonService.SysManager.IC_Userinfo>("UserinfoWCF");
            _roleRolePowerWCF = ServiceProxyFactory.Create<ICommonService.SysManager.IC_Role_Role_Power>("Role_Role_PowerWCF");
            _parameterWCF = ServiceProxyFactory.Create<ICommonService.IC_Parameters>("parametersWCF");
        }

        //
        // GET: /BaseData/CustomerExecute/
        public override ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 客户执行布局页Action
        /// </summary>
        /// <param name="customerCode">客户Guid</param>
        /// <returns></returns>
        public ActionResult DefaultLayout(string customerCode)
        {
            List<CommonService.Model.FlowManager.P_Business_flow> BusinessFlows = _bussinessFlowWCF.GetListByFkCodeAndLevel(new Guid(customerCode), 1);
            CommonService.Model.C_Customer Customer = _customerWCF.Get(new Guid(customerCode));
            this.InitializationPageParameter(Customer);

            ViewBag.Customer = Customer;//客户数据模型
            ViewBag.FkType = Convert.ToInt32(FlowTypeEnum.客户);//流程类型

            #region 数据权限
            List<CommonService.Model.SysManager.C_Role_Role_Power> roleRolePowers;
            if (Context.UIContext.Current.IsPreSetManager)
            {
                roleRolePowers = new List<CommonService.Model.SysManager.C_Role_Role_Power>();
            }
            else
            {
                roleRolePowers = _roleRolePowerWCF.GetRolePowersByOrgPostUserCode(Context.UIContext.Current.OrgCode,
                    Context.UIContext.Current.UserCode,Context.UIContext.Current.PostCode);
            }
            ViewBag.RoleRolePowers = roleRolePowers;

            bool isCustomerConsultant = false;//当前登录用户是否此客户专业顾问
            if (!Context.UIContext.Current.IsPreSetManager)
            {
                //当前客户专业顾问
                if (Customer.C_Customer_consultant != null && Context.UIContext.Current.UserCode == Customer.C_Customer_consultant)
                {
                    isCustomerConsultant = true;
                }
            }

            ViewBag.IsCustomerConsultant = isCustomerConsultant;
            #endregion

            #region 按钮权限

            /**
             * author:hety
             * date:2015-11-24
             * descption:
             * 在客户未启动的情况下，"客户启动"按钮，根据当前用户是否拥有此按钮的权限来控制(内置系统管理员除外)
             ***/
            bool isShowStartBtn = false;//是否显示"客户启动"按钮
            if (Customer != null)
            {
                if (Customer.C_Customer_goingStatus == Convert.ToInt32(BusinessFlowStatus.未开始))
                {
                    if (Context.UIContext.Current.IsPreSetManager)
                    {
                        isShowStartBtn = true;
                    }
                    else
                    {
                        this.DistributedInitButtonsPower(Context.UIContext.Current.OrgCode,Context.UIContext.Current.PostCode);
                        List<CommonService.Model.SysManager.C_Role_button> RoleButtons = ViewBag.RoleButtons;
                        if (RoleButtons.Where(r => r.C_Menu_buttons_id == 1163).Count() != 0)
                        {//存在"启动任务"的按钮，按钮标识为：1163
                            isShowStartBtn = true;
                        }
                    }
                }
            }
            ViewBag.IsShowStartBtn = isShowStartBtn;
            #endregion

            return View(BusinessFlows);
        }

        #region 客户计划相关

        /// <summary>
        /// 显示设置客户计划
        /// </summary>       
        /// <param name="customerCode">客户Guid</param>
        /// <returns></returns>
        public ActionResult ShowSetCustomerPlan(string customerCode)
        {
            /**
             * 查看此界面时，要将老客户里面的负责人和首席专家根据专业顾问添加相应的数据 --cyj
             * 
             * **/
            _customerWCF.SetMinisterAndChiefResponsible(customerCode, UIContext.Current.OrgCode);
            CommonService.Model.C_Customer Customer = _customerWCF.Get(new Guid(customerCode));//客户数据模型  
            //负责人
            List<CommonService.Model.SysManager.C_Userinfo> responsiblePersons = _userinfoWCF.GetAllChildList(1);
            if (responsiblePersons.Count() == 0)
            {
                if (Customer.C_Customer_responsiblePerson != null)
                {
                    CommonService.Model.SysManager.C_Userinfo uModel = _userinfoWCF.GetModelByUserCode(Customer.C_Customer_responsiblePerson.Value);
                    if (uModel != null)
                    {
                        responsiblePersons.Add(uModel);
                    }
                }

            }
            ViewBag.ResponsiblePersons = responsiblePersons;

            //首席负责人
            List<CommonService.Model.SysManager.C_Userinfo> chiefResponsiblePersons = _userinfoWCF.GetAllChildList(2);
            if (chiefResponsiblePersons.Count() == 0)
            {
                if (Customer.C_Customer_chiefResponsiblePerson != null)
                {
                    CommonService.Model.SysManager.C_Userinfo uModel = _userinfoWCF.GetModelByUserCode(Customer.C_Customer_chiefResponsiblePerson.Value);
                    if (uModel != null)
                    {
                        chiefResponsiblePersons.Add(uModel);
                    }
                }

            }
            ViewBag.CiefResponsiblePersons = chiefResponsiblePersons;



            #region 是否显示"保存"按钮(客户负责人或者客户首席负责人或专业顾问或内置系统管理员有此按钮权限)
            bool isShowSaveBtn = false;
            if (Context.UIContext.Current.IsPreSetManager)
            {
                isShowSaveBtn = true;
            }
            else
            {
                if (Customer.C_Customer_responsiblePerson != null)
                {//客户负责人
                    if (Customer.C_Customer_responsiblePerson == Context.UIContext.Current.UserCode)
                    {
                        isShowSaveBtn = true;
                    }
                }
                if (Customer.C_Customer_chiefResponsiblePerson != null)
                {//客户首席负责人
                    if (Customer.C_Customer_chiefResponsiblePerson == Context.UIContext.Current.UserCode)
                    {
                        isShowSaveBtn = true;
                    }
                }
                if (!isShowSaveBtn)
                {//专业顾问                   
                    if (Customer.C_Customer_consultant != null && Customer.C_Customer_consultant == Context.UIContext.Current.UserCode)
                    {
                        isShowSaveBtn = true;
                    }
                }

            }
            ViewBag.IsShowSaveBtn = isShowSaveBtn;
            #endregion

            #region 客户首席负责人或内置系统管理员，拥有所有修改页面数据的权限；而客户负责人或专业顾问，只可以修改计划时间
            int editPagePropertyType = 0;//修改页面元素类型
            if (Context.UIContext.Current.IsPreSetManager)
            {
                editPagePropertyType = 1;//代表修改所有元素
            }
            else
            {
                if (Customer.C_Customer_responsiblePerson != null)
                {//客户负责人
                    if (Customer.C_Customer_responsiblePerson == Context.UIContext.Current.UserCode)
                    {
                        editPagePropertyType = 2;//只可修改计划时间
                    }
                }

                if (editPagePropertyType != 2)
                {//专业顾问

                    if (Customer.C_Customer_consultant != null && Customer.C_Customer_consultant == Context.UIContext.Current.UserCode)
                    {
                        editPagePropertyType = 2;//只可修改计划时间
                    }
                }

                if (Customer.C_Customer_chiefResponsiblePerson != null)
                {//客户首席负责人
                    if (Customer.C_Customer_chiefResponsiblePerson == Context.UIContext.Current.UserCode)
                    {
                        editPagePropertyType = 1;//代表修改所有元素
                    }
                }
            }
            ViewBag.EditPagePropertyType = editPagePropertyType;
            #endregion

            return View("ShowSetCustomerPlan", Customer);
        }

        /// <summary>
        /// 保存客户计划
        /// </summary>
        /// <param name="form"></param>
        /// <param name="customer">客户数据模型</param>
        /// <returns></returns>
        public ActionResult SetCustomerPlan(FormCollection form, CommonService.Model.C_Customer customer)
        {
            if (DateTime.Compare(customer.C_Customer_planStartTime.Value, customer.C_Customer_planEndTime.Value) < 0)
            {
                if (form["C_Customer_chiefResponsiblePerson"] != "请选择")
                {
                    customer.C_Customer_chiefResponsiblePerson = new Guid(form["C_Customer_chiefResponsiblePerson"]);
                }
                else
                {

Erp/Portal/Areas/BaseData/Views/CustomerExecute/ShowSetCustomerPlan.cshtml
@model CommonService.Model.C_Customer
@{
    Layout = "~/Views/Shared/_EditDialogFormTemplate.cshtml";//带表单提交的编辑页面固定模板
}
@{
    ViewBag.Title = "客户计划";
}

@section HeadScript{
    <script type="text/javascript">
        document.onkeyup = function (e) {      //onkeyup是javascript的一个事件、当按下某个键弹起 var _key; //的时触发
            if (e == null) { // ie
                _key = event.keyCode;
            } else { // firefox              //获取你按下键的keyCode
                _key = e.which;          //每个键的keyCode是不一样的
            }
            if (_key == 13) {   //判断keyCode是否是13，也就是回车键(回车的keyCode是13)
                onlySaveForm(document.getElementById('btnSave'));
            }
        }
        $(function () {
            var editPagePropertyType = '@ViewBag.EditPagePropertyType';//修改页面元素类型(控制可编辑项)
            if (editPagePropertyType == '0') {
                $('#C_Customer_chiefResponsiblePerson').attr('disabled', 'true');
                $('#C_Customer_responsiblePerson').attr('disabled', 'true');
                $('#C_Customer_planStartTime').attr('disabled', 'true');
                $('#C_Customer_planEndTime').attr('disabled', 'true');
            } else if (editPagePropertyType == '2') {
                $('#C_Customer_chiefResponsiblePerson').attr('disabled', 'true');
                $('#C_Customer_responsiblePerson').attr('disabled', 'true');
            }

        })
    </script>
}
@section HeadCss
{
    <style type="text/css">
        .formbody {
            padding: 10px 5px;
        }
        .forminfo {
            padding-left: 0px;
        }
        .mulitytext {
            width: auto;
        }
        .mulitytext label {
            width: 100px;
        }
        .mulitytext a {
            line-height: 21px;
        }
        .mulitytext i {
            margin-left: 0px;
        }
    </style>
}
@{
    List<CommonService.Model.SysManager.C_Userinfo> ciefResponsiblePersons = ViewBag.CiefResponsiblePersons;//首席负责人集合
    List<CommonService.Model.SysManager.C_Userinfo> responsiblePersons = ViewBag.ResponsiblePersons;//负责人集合    
    bool isShowSaveBtn = ViewBag.IsShowSaveBtn;//是否显示"保存"按钮
}
<div class="formbody">
    <div class="forminfo">
        @using (Html.BeginForm("SetCustomerPlan", "CustomerExecute", FormMethod.Post, new { id = "customerPlanForm", onsubmit = "return validateCallback(this,dialogAjaxDone);" }))
        {          
            @Html.Hidden("C_Customer_code", Model.C_Customer_code) 
            <div class="mulitytext">
                <label>首席专家：</label>
                @{
                   IList<SelectListItem> auserItems = new List<SelectListItem>();
                   SelectListItem selectItemone = new SelectListItem();
                   selectItemone.Value = null;
                   selectItemone.Text = "请选择";
                   auserItems.Add(selectItemone);
                   foreach (var firstUser in ciefResponsiblePersons)
                   {
                      SelectListItem selectItem = new SelectListItem();
                      selectItem.Value = firstUser.C_Userinfo_code.ToString();
                      selectItem.Text = firstUser.C_Userinfo_name;
                      if (Model.C_Customer_chiefResponsiblePerson != null)
                      {
                          if (Model.C_Customer_chiefResponsiblePerson.ToString() == selectItem.Value.ToString())
                         {
                            selectItem.Selected = true;
                         }
                      }
                      auserItems.Add(selectItem);
                   }
                }
                @Html.DropDownList("C_Customer_chiefResponsiblePerson", auserItems, new { requiredInput = "请选择负责人" })<i></i>
            </div>
            <div class="mulitytext">
                <label>部长：</label>
                @{
                    IList<SelectListItem> userItems = new List<SelectListItem>();
                    userItems.Add(selectItemone);
                    foreach (var user in responsiblePersons)
                    {
                      SelectListItem selectItem = new SelectListItem();
                      selectItem.Value = user.C_Userinfo_code.ToString();
                      selectItem.Text = user.C_Userinfo_Organization_name + "->" + user.C_Userinfo_name;

                      userItems.Add(selectItem);
                    }
                }
                @Html.DropDownList("C_Customer_responsiblePerson", userItems, new { requiredInput = "请选择负责人" })<i></i>
            </div>
            <div class="mulitytext"><label>计划开始时间：</label>@Html.TextBox("C_Customer_planStartTime", Model.C_Customer_planStartTime == null ? "" : Model.C_Customer_planStartTime.Value.ToString("yyyy-MM-dd HH:mm:ss"), new { date = "date", maxlength = "20", @readonly = "readonly", dateformat = "yyyy-MM-dd HH:mm:ss", @class = "dfinput", requiredinput = "请选择日期" })<i></i></div>
            <div class="mulitytext"><label>计划结束时间：</label>@Html.TextBox("C_Customer_planEndTime", Model.C_Customer_planEndTime == null ? "" : Model.C_Customer_planEndTime.Value.ToString("yyyy-MM-dd HH:mm:ss"), new { date = "date", maxlength = "20", @readonly = "readonly", dateformat = "yyyy-MM-dd HH:mm:ss", @class = "dfinput", requiredinput = "请选择日期" })<i></i></div>
            if (isShowSaveBtn)
            {
                <div class="mulitytext"><a id="btnSave" class="tablelink" onclick="onlySaveForm(this)" href="javascript:void(0);">保存</a></div>
            }
        }
    </div>
</div>