Erp/Portal/Areas/BusinessChanceManager/Controllers/ChancePlanController.cs
using Maticsoft.Common;
using Portal.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portal.Areas.BusinessChanceManager.Controllers
{
    /// <summary>
    /// 商机计划Control
    /// </summary>
    public class ChancePlanController : BaseController
    {
        private readonly ICommonService.SysManager.IC_Userinfo _userinfoWCF;
        private readonly ICommonService.BusinessChanceManager.IB_BusinessChance _businessChanceWCF;
        private readonly ICommonService.BusinessChanceManager.IB_BusinessChance_link _businessChance_linkWCF;

        public ChancePlanController()
        {
            _userinfoWCF = ServiceProxyFactory.Create<ICommonService.SysManager.IC_Userinfo>("UserinfoWCF");
            _businessChanceWCF = ServiceProxyFactory.Create<ICommonService.BusinessChanceManager.IB_BusinessChance>("BusinessChanceWCF");
            _businessChance_linkWCF = ServiceProxyFactory.Create<ICommonService.BusinessChanceManager.IB_BusinessChance_link>("BusinessChance_linkWCF");
        }

        //
        // GET: /BusinessChanceManager/ChancePlan/
        public override ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 显示设置商机计划
        /// </summary>
        /// <param name="fkType">流程类型(只为商机)</param>
        /// <param name="pkCode">商机Guid</param>
        /// <returns></returns>
        public ActionResult ShowSetChangePlan(string fkType, string pkCode)
        {
            //专家部长
            List<CommonService.Model.SysManager.C_Userinfo> users = _userinfoWCF.GetAllChildList(1);
            ViewBag.users = users;
            //首席
            List<CommonService.Model.SysManager.C_Userinfo> firstUsers = _userinfoWCF.GetAllChildList(2);
            ViewBag.firstUsers = firstUsers;

            CommonService.Model.BusinessChanceManager.B_BusinessChance businessChance = _businessChanceWCF.GetModel(new Guid(pkCode));

            #region 是否显示"保存"按钮(商机负责人或者一级负责人或专业顾问或内置系统管理员有此按钮权限)
            bool isShowSaveBtn = false;
            if (Context.UIContext.Current.IsPreSetManager)
            {
                isShowSaveBtn = true;
            }
            else
            {
                if (businessChance.B_BusinessChance_person != null)
                {//商机负责人
                    if (businessChance.B_BusinessChance_person == Context.UIContext.Current.UserCode)
                    {
                        isShowSaveBtn = true;
                    }
                }
                if (businessChance.B_BusinessChance_firstClassResponsiblePerson != null)
                {//一级负责人
                    if (businessChance.B_BusinessChance_firstClassResponsiblePerson == Context.UIContext.Current.UserCode)
                    {
                        isShowSaveBtn = true;
                    }
                }
                if (!isShowSaveBtn)
                {//专业顾问
                    List<CommonService.Model.BusinessChanceManager.B_BusinessChance_link> businessChanceLinks = _businessChance_linkWCF.GetBusinessChanceLinks(new Guid(pkCode), 5);
                    if (businessChanceLinks.Where(p => p.C_FK_code == Context.UIContext.Current.UserCode).Count() != 0)
                    {
                        isShowSaveBtn = true;
                    }
                }

            }
            ViewBag.IsShowSaveBtn = isShowSaveBtn;
            #endregion

            #region 一级负责人或内置系统管理员，拥有所有修改页面数据的权限；而二级负责人或专业顾问，只可以修改计划时间
            int editPagePropertyType = 0;//修改页面元素类型
            if (Context.UIContext.Current.IsPreSetManager)
            {
                editPagePropertyType = 1;//代表修改所有元素
            }
            else
            {
                if (businessChance.B_BusinessChance_person != null)
                {//二级负责人
                    if (businessChance.B_BusinessChance_person == Context.UIContext.Current.UserCode)
                    {
                        editPagePropertyType = 2;//只可修改计划时间
                    }
                }

                if (editPagePropertyType != 2)
                {//专业顾问
                    List<CommonService.Model.BusinessChanceManager.B_BusinessChance_link> businessChanceLinks = _businessChance_linkWCF.GetBusinessChanceLinks(new Guid(pkCode), 5);
                    if (businessChanceLinks.Where(p => p.C_FK_code == Context.UIContext.Current.UserCode).Count() != 0)
                    {
                        editPagePropertyType = 2;//只可修改计划时间
                    }
                }

                if (businessChance.B_BusinessChance_firstClassResponsiblePerson != null)
                {//一级负责人
                    if (businessChance.B_BusinessChance_firstClassResponsiblePerson == Context.UIContext.Current.UserCode)
                    {
                        editPagePropertyType = 1;//代表修改所有元素
                    }
                }
            }
            ViewBag.EditPagePropertyType = editPagePropertyType;
            #endregion

            return View("SetChangePlan", businessChance);
        }

        /// <summary>
        /// 设置商机计划
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult SetChangePlan(FormCollection form, CommonService.Model.BusinessChanceManager.B_BusinessChance businessChance)
        {
            if (DateTime.Compare(businessChance.B_BusinessChance_planStartTime.Value, businessChance.B_BusinessChance_planEndTime.Value) < 0)
            {
                if (form["B_BusinessChance_firstClassResponsiblePerson"] != "请选择")
                {
                    businessChance.B_BusinessChance_firstClassResponsiblePerson = new Guid(form["B_BusinessChance_firstClassResponsiblePerson"]);
                }
                else
                {
                    businessChance.B_BusinessChance_firstClassResponsiblePerson = null;
                }
                if (form["B_BusinessChance_person"] != "请选择")
                {
                    businessChance.B_BusinessChance_person = new Guid(form["B_BusinessChance_person"]);
                }
                else
                {
                    businessChance.B_BusinessChance_person = null;
                }
                businessChance.B_BusinessChance_planStartTime = Convert.ToDateTime(form["B_BusinessChance_planStartTime"]);
                businessChance.B_BusinessChance_planEndTime = Convert.ToDateTime(form["B_BusinessChance_planEndTime"]);
                bool isUpdateSuccess = _businessChanceWCF.Update(businessChance);
                if (isUpdateSuccess)
                {
                    //保存成功提示固定写法
                    return Json(TipHelper.JsonData("设定计划信息成功！", "", IsAlertTip.Yes, TipType.Success, AlertTipPageType.ParentPage, OperateTypeAfterTip.CloseTipAndRefreshThisPage));                   
                }
                else
                {
                    //保存失败固定写法
                    return Json(TipHelper.JsonData("设定计划信息失败！", "", IsAlertTip.Yes, TipType.Error, AlertTipPageType.ParentPage, OperateTypeAfterTip.NoAction));
                }
            }
            else
            {
                return Json(TipHelper.JsonData("计划开始时间不能大于计划结束时间！", "", IsAlertTip.Yes, TipType.Error, AlertTipPageType.ParentPage, OperateTypeAfterTip.NoAction));
            }
        }

	}
}

Erp/Portal/Areas/BusinessChanceManager/Views/ChancePlan/SetChangePlan.cshtml
@model CommonService.Model.BusinessChanceManager.B_BusinessChance
@{
    Layout = "~/Views/Shared/_EditDialogFormTemplate.cshtml";//带表单提交的编辑页面固定模板
}
@{
    ViewBag.Title = "商机计划";
}
@{
    List<CommonService.Model.SysManager.C_Userinfo> users = ViewBag.users;
    List<CommonService.Model.SysManager.C_Userinfo> firstUsers = ViewBag.firstUsers;
    bool isShowSaveBtn = ViewBag.IsShowSaveBtn;//是否显示"保存"按钮   
}
@section HeadScript{
    <script type="text/javascript">
        document.onkeyup = function (e) {      //onkeyup是javascript的一个事件、当按下某个键弹起 var _key; //的时触发
            if (e == null) { // ie
                _key = event.keyCode;
            } else { // firefox              //获取你按下键的keyCode
                _key = e.which;          //每个键的keyCode是不一样的
            }
            if (_key == 13) {   //判断keyCode是否是13，也就是回车键(回车的keyCode是13)
                onlySaveForm(document.getElementById('btnSave'));
            }
        }
        $(function () {           
            var editPagePropertyType = '@ViewBag.EditPagePropertyType';//修改页面元素类型(控制可编辑项)
            if (editPagePropertyType == '0') {
                $('#B_BusinessChance_firstClassResponsiblePerson').attr('disabled', 'true');
                $('#B_BusinessChance_person').attr('disabled', 'true');
                $('#B_BusinessChance_planStartTime').attr('disabled', 'true');
                $('#B_BusinessChance_planEndTime').attr('disabled', 'true');
            } else if (editPagePropertyType == '2') {
                $('#B_BusinessChance_firstClassResponsiblePerson').attr('disabled', 'true');
                $('#B_BusinessChance_person').attr('disabled', 'true');
            }
       
        })
    </script>
}
@section HeadCss
{
    <style type="text/css">
        .formbody {
            padding: 10px 5px;
        }
        .forminfo{padding-left:0px;}
        .mulitytext {
            width: auto;
        }
        .mulitytext label{
            width:100px;
        }
        .mulitytext a{
            line-height:21px;
        }
       .mulitytext i{margin-left:0px;}
    </style>
}
<div class="formbody">
    <ul class="forminfo">
        @using (Html.BeginForm("SetChangePlan", "ChancePlan", FormMethod.Post, new { id = "changePlanForm", onsubmit = "return validateCallback(this,dialogAjaxDone);" }))
        {
            @Html.Hidden("B_BusinessChance_id", Model.B_BusinessChance_id)
            @Html.Hidden("B_BusinessChance_code", Model.B_BusinessChance_code)
            @Html.Hidden("B_BusinessChance_state", Model.B_BusinessChance_state)
            @Html.Hidden("B_BusinessChance_checkStatus", Model.B_BusinessChance_checkStatus)
            @Html.Hidden("B_BusinessChance_creator", Model.B_BusinessChance_creator)
            @Html.Hidden("B_BusinessChance_createTime", Model.B_BusinessChance_createTime)
            @Html.Hidden("B_BusinessChance_isDelete", Model.B_BusinessChance_isDelete)
            @Html.Hidden("B_BusinessChance_name", Model.B_BusinessChance_name)
            @Html.Hidden("B_BusinessChance_number", Model.B_BusinessChance_number)
            @Html.Hidden("B_BusinessChance_type", Model.B_BusinessChance_type)
            @Html.Hidden("B_BusinessChance_customerType", Model.B_BusinessChance_customerType)
            @Html.Hidden("B_BusinessChance_Customer_code", Model.B_BusinessChance_Customer_code)
            @Html.Hidden("B_BusinessChance_Competitor", Model.B_BusinessChance_Competitor)
            @Html.Hidden("B_BusinessChance_registerTime", Model.B_BusinessChance_registerTime)
            @Html.Hidden("B_BusinessChance_Project_code", Model.B_BusinessChance_Project_code)
            @Html.Hidden("B_BusinessChance_expectedTarget", Model.B_BusinessChance_expectedTarget)
            @Html.Hidden("B_BusinessChance_Region_code", Model.B_BusinessChance_Region_code)
            @Html.Hidden("B_BusinessChance_successProbability", Model.B_BusinessChance_successProbability)
            @Html.Hidden("B_BusinessChance_obtainTime", Model.B_BusinessChance_obtainTime)
            @Html.Hidden("B_BusinessChance_Client_code", Model.B_BusinessChance_Client_code)
            @Html.Hidden("B_BusinessChance_Case_nature", Model.B_BusinessChance_Case_nature)
            @Html.Hidden("B_BusinessChance_courtFirst", Model.B_BusinessChance_courtFirst)
            @Html.Hidden("B_BusinessChance_courtSecond", Model.B_BusinessChance_courtSecond)
            @Html.Hidden("B_BusinessChance_courtExec", Model.B_BusinessChance_courtExec)
            @Html.Hidden("B_BusinessChance_transferTargetMoney", Model.B_BusinessChance_transferTargetMoney)
            @Html.Hidden("B_BusinessChance_transferTargetOther", Model.B_BusinessChance_transferTargetOther)
            @Html.Hidden("B_BusinessChance_expectedGrant", Model.B_BusinessChance_expectedGrant)
            @Html.Hidden("B_BusinessChance_execMoney", Model.B_BusinessChance_execMoney)
            @Html.Hidden("B_BusinessChance_execOther", Model.B_BusinessChance_execOther)
            @Html.Hidden("B_BusinessChance_Person_code", Model.B_BusinessChance_Person_code)
            @Html.Hidden("B_BusinessChance_Outline", Model.B_BusinessChance_Outline)
            @Html.Hidden("B_BusinessChance_remark", Model.B_BusinessChance_remark)
            @Html.Hidden("B_BusinessChance_Requirement", Model.B_BusinessChance_Requirement)
            @Html.Hidden("B_BusinessChance_remarks", Model.B_BusinessChance_remarks)
            @Html.Hidden("B_BusinessChance_factStartTime", Model.B_BusinessChance_factStartTime)
            @Html.Hidden("B_BusinessChance_factEndTime", Model.B_BusinessChance_factEndTime)
            
            <div class="mulitytext">
                <label>首席专家：</label>
                @{
                    IList<SelectListItem> auserItems = new List<SelectListItem>();
                    SelectListItem selectItemone = new SelectListItem();
                    selectItemone.Value = null;
                    selectItemone.Text = "请选择";
                    auserItems.Add(selectItemone);
                    foreach (var firstUser in firstUsers)
                    {
                       SelectListItem selectItem = new SelectListItem();
                selectItem.Value = firstUser.C_Userinfo_code.ToString();
                selectItem.Text = firstUser.C_Userinfo_name;
                if (Model.B_BusinessChance_firstClassResponsiblePerson != null)
                {
                    if (Model.B_BusinessChance_firstClassResponsiblePerson.ToString() == selectItem.Value.ToString())
                    {
                        selectItem.Selected = true;
                    }
                }
                auserItems.Add(selectItem);
            }
                }
                @Html.DropDownList("B_BusinessChance_firstClassResponsiblePerson", auserItems, new {requiredInput = "请选择负责人" })<i></i>
            </div>
            <div class="mulitytext">
                <label>部长：</label>
                @{
            IList<SelectListItem> userItems = new List<SelectListItem>();
            userItems.Add(selectItemone);
            foreach (var user in users)
            {
                SelectListItem selectItem = new SelectListItem();
                selectItem.Value = user.C_Userinfo_code.ToString();
                selectItem.Text = user.C_Userinfo_Organization_name + "->" + user.C_Userinfo_name;

                userItems.Add(selectItem);
            }
                }
                @Html.DropDownList("B_BusinessChance_person", userItems, new {requiredInput = "请选择负责人" })<i></i>
            </div>
            <div class="mulitytext"><label>计划开始时间：</label>@Html.TextBox("B_BusinessChance_planStartTime", Model.B_BusinessChance_planStartTime == null ? "" : Model.B_BusinessChance_planStartTime.Value.ToString("yyyy-MM-dd HH:mm:ss"), new { date = "date", maxlength = "20", @readonly = "readonly", dateformat = "yyyy-MM-dd HH:mm:ss", @class = "dfinput", requiredinput = "请选择日期" })<i></i></div>
            <div class="mulitytext"><label>计划结束时间：</label>@Html.TextBox("B_BusinessChance_planEndTime", Model.B_BusinessChance_planEndTime == null ? "" : Model.B_BusinessChance_planEndTime.Value.ToString("yyyy-MM-dd HH:mm:ss"), new { date = "date", maxlength = "20", @readonly = "readonly", dateformat = "yyyy-MM-dd HH:mm:ss", @class = "dfinput", requiredinput = "请选择日期" })<i></i></div>           
            if (isShowSaveBtn)
            {
                <div class="mulitytext"><a id="btnSave" class="tablelink" onclick="onlySaveForm(this)" href="javascript:void(0);">保存</a></div> 
            } 
                      
        }
    </ul>
</div>