Erp/Portal/Areas/BaseData/Controllers/Involved_projectController.cs
using CommonService.Common;
using Maticsoft.Common;
using Portal.Controllers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portal.Areas.BaseData.Controllers
{
    /// <summary>
    /// 涉案项目控制器
    ///  作者：崔慧栋
    /// 日期：2015/05/13
    /// </summary>
    public class Involved_projectController : BaseController
    {
        private readonly ICommonService.IC_Involved_project _involved_projectWCF;
        public Involved_projectController()
        {
            #region 服务初始化
            _involved_projectWCF = ServiceProxyFactory.Create<ICommonService.IC_Involved_project>("Involved_projectWCF");
            #endregion
        }
        //
        // GET: /BaseData/Involved_project/
        public override ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 创建
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            //创建初始化涉案项目实体
            CommonService.Model.C_Involved_project involved_project = new CommonService.Model.C_Involved_project();
            involved_project.C_Involved_project_code = Guid.NewGuid();
            involved_project.C_Involved_project_createTime = DateTime.Now;
            involved_project.C_Involved_project_creator = Context.UIContext.Current.UserCode;
            involved_project.C_Involved_project_isDelete =0;

            return View(involved_project);
        }

        /// <summary>
        /// 编辑
        /// </summary>
        /// <returns></returns>
        public ActionResult Edit(string Involved_project_code)
        {
            CommonService.Model.C_Involved_project involved_project = _involved_projectWCF.GetModelByCode(new Guid(Involved_project_code));
            return View("Create", involved_project);
        }


        /// <summary>
        /// tab 页签
        /// </summary>
        /// <returns></returns>
        public ActionResult TabDetails(string Involved_project_code)
        {
            ViewBag.Involved_project_code = Involved_project_code;
            return View();
        }

        /// <summary>
        /// tab 页签
        /// </summary>
        /// <returns></returns>
        public ActionResult CutTabDetails(string Involved_project_code)
        {
            ViewBag.Involved_project_code = Involved_project_code;
            return View();
        }

        /// <summary>
        /// 详细
        /// </summary>
        /// <returns></returns>
        public ActionResult Details(string Involved_project_code)
        {
            CommonService.Model.C_Involved_project project = _involved_projectWCF.GetModelByCode(new Guid(Involved_project_code));
            return View(project);
        }


        /// <summary>
        /// 列表
        /// </summary>
        /// <param name="page">当前页码</param>
        /// <returns></returns>
        public ActionResult List(FormCollection form, int? page = 1)
        {
            #region 查询模型条件设置,查询条件都根据实际业务进行相应更改)

            //涉案项目查询模型
            CommonService.Model.C_Involved_project projectConditon = new CommonService.Model.C_Involved_project();

            if (!String.IsNullOrEmpty(form["C_Involved_project_name"]))
            {//涉案项目名称查询条件
                projectConditon.C_Involved_project_name = form["C_Involved_project_name"].Trim();
            }
            // 
            if (!String.IsNullOrEmpty(form["C_Involved_project_address"]))
            {//涉案地点查询条件
                projectConditon.C_Involved_project_address = form["C_Involved_project_address"].Trim();
            }
            if (!String.IsNullOrEmpty(form["C_Involved_project_type"]))
            {//涉案类别
                projectConditon.C_Involved_project_type = form["C_Involved_project_type"].Trim();
            }
            //C_Involved_project_type
            //涉案项目查询模型传递到前端视图中
            ViewBag.ProjectConditon = projectConditon;

            #endregion

            //获取涉案项目总记录数
            this.TotalRecordCount = _involved_projectWCF.GetRecordCount(projectConditon);

            //初始化页面信息(固定写法)
            this.InitializationPageInfo(form, page.Value);

            //获取涉案项目数据信息
            List<CommonService.Model.C_Involved_project> projects = _involved_projectWCF.GetListByPage(projectConditon,
                "", (this.ThisPageIndex - 1) * this.PageSize + 1, this.ThisPageIndex * this.PageSize);

            #region 权限
            this.InitializationButtonsPower();
            #endregion

            return View(projects);
        }

        /// <summary>
        /// 单选回调工程列表
        /// </summary>
        /// <param name="form"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult SingleCallbackRefList(FormCollection form,int? page = 1)
        {
            #region 查询模型条件设置,查询条件都根据实际业务进行相应更改)

            //涉案项目查询模型
            CommonService.Model.C_Involved_project projectConditon = new CommonService.Model.C_Involved_project();

            if (!String.IsNullOrEmpty(form["C_Involved_project_name"]))
            {//涉案项目名称查询条件
                projectConditon.C_Involved_project_name = form["C_Involved_project_name"].Trim();
            }
            //涉案项目查询模型传递到前端视图中
            ViewBag.ProjectConditon = projectConditon;

            #endregion

            //获取涉案项目总记录数
            this.TotalRecordCount = _involved_projectWCF.GetRecordCount(projectConditon);

            //初始化页面信息(固定写法)
            this.InitializationPageInfo(form, page.Value);
            this.PageSize = 8;
            //获取涉案项目数据信息
            List<CommonService.Model.C_Involved_project> projects = _involved_projectWCF.GetListByPage(projectConditon,
                "", (this.ThisPageIndex - 1) * this.PageSize + 1, this.ThisPageIndex * this.PageSize);

            return View(projects);
        }
        /// <summary>
        /// 单选回调法院列表(自定义表单调用)
        /// </summary>
        /// <param name="form">查询表单</param>
        /// <param name="lookupgroup">单选弹出分组</param>
        /// <param name="propertyValueCode">表单属性值Guid</param>
        /// <param name="mappingField">映射字段(这个字段值要保存到属性值表中"值字段")</param>
        /// <param name="mappingFieldName">映射字段显示字段(只用来做界面显示)</param>
        /// <param name="page">页码</param>
        /// <returns></returns>
        public ActionResult SingleCallbackRefList_ProjectForm(FormCollection form, string lookupgroup, string propertyValueCode, string mappingField, string mappingFieldName, int? page = 1)
        {
            #region 查询模型条件设置,查询条件都根据实际业务进行相应更改)

            //涉案项目查询模型
            CommonService.Model.C_Involved_project projectConditon = new CommonService.Model.C_Involved_project();

            if (!String.IsNullOrEmpty(form["C_Involved_project_name"]))
            {//涉案项目名称查询条件
                projectConditon.C_Involved_project_name = form["C_Involved_project_name"].Trim();
            }
            //涉案项目查询模型传递到前端视图中
            ViewBag.ProjectConditon = projectConditon;
            this.PageSize = 8;
            #endregion

            #region 参照配置条件
            string _lookupgroup = String.Empty;
            string _propertyValueCode = String.Empty;
            string _mappingField = String.Empty;
            string _mappingFieldName = String.Empty;

            if (!String.IsNullOrEmpty(form["lookupgroup"]))
            {
                _lookupgroup = form["lookupgroup"];
            }
            if (!String.IsNullOrEmpty(form["propertyValueCode"]))
            {
                _propertyValueCode = form["propertyValueCode"];
            }
            if (!String.IsNullOrEmpty(lookupgroup))
            {
                _lookupgroup = lookupgroup;
            }
            if (!String.IsNullOrEmpty(propertyValueCode))
            {
                _propertyValueCode = propertyValueCode;
            }
            ViewBag.Lookupgroup = _lookupgroup;
            ViewBag.PropertyValueCode = _propertyValueCode;
            ViewBag.MappingField = _mappingField;
            ViewBag.MappingFieldName = _mappingFieldName;

            this.AddressUrlParameters = "?lookupgroup=" + _lookupgroup;//加入地址栏条件
            this.AddressUrlParameters = this.AddressUrlParameters + "&propertyValueCode=" + _propertyValueCode;

            #endregion
            //获取涉案项目总记录数
            this.TotalRecordCount = _involved_projectWCF.GetRecordCount(projectConditon);

            //初始化页面信息(固定写法)
            this.InitializationPageInfo(form, page.Value);

            //获取涉案项目数据信息
            List<CommonService.Model.C_Involved_project> projects = _involved_projectWCF.GetListByPage(projectConditon,
                "", (this.ThisPageIndex - 1) * this.PageSize + 1, this.ThisPageIndex * this.PageSize);

            return View(projects);
        }
        /// <summary>
        /// 多选回调工程列表
        /// </summary>
        /// <param name="form"></param>
        /// <param name="page"></param>
        /// <returns></returns>
        public ActionResult MulityCallbackRefList(FormCollection form,string checkedProjectCode, int? page = 1)
        {
            #region 查询模型条件设置,查询条件都根据实际业务进行相应更改)

            //涉案项目查询模型
            CommonService.Model.C_Involved_project projectConditon = new CommonService.Model.C_Involved_project();

            if (!String.IsNullOrEmpty(form["C_Involved_project_name"]))
            {//涉案项目名称查询条件
                projectConditon.C_Involved_project_name = form["C_Involved_project_name"].Trim();
            }
            //涉案项目查询模型传递到前端视图中
            ViewBag.ProjectConditon = projectConditon;
            ViewBag.checkedProjectCode = checkedProjectCode;
            #endregion

            //获取涉案项目总记录数
            this.TotalRecordCount = _involved_projectWCF.GetRecordCount(projectConditon);

            //初始化页面信息(固定写法)
            this.InitializationPageInfo(form, page.Value);
            this.PageSize = 10;

            //获取涉案项目数据信息

Erp/Portal/Areas/BaseData/Views/Involved_project/Create.cshtml
@model CommonService.Model.C_Involved_project
@{
    Layout = "~/Views/Shared/_EditDialogFormTemplate.cshtml";//带表单提交的编辑页面固定模板
}
@{
    ViewBag.Title = "涉案项目";
}
@section HeadScript{
    <script type="text/javascript">
        document.onkeyup = function (e) {      //onkeyup是javascript的一个事件、当按下某个键弹起 var _key; //的时触发 
            if (e == null) { // ie  
                _key = event.keyCode;
            } else { // firefox              //获取你按下键的keyCode  
                _key = e.which;          //每个键的keyCode是不一样的  
            }
            if (_key == 13) {   //判断keyCode是否是13，也就是回车键(回车的keyCode是13)  
                onlySaveForm(document.getElementById('btnSave'));
            }
        }
    </script>
}
<div class="formbody">
    <div class="formtitle"><span>基本信息</span></div>
    <ul class="forminfo">
        @using (Html.BeginForm("Save", "Involved_project", FormMethod.Post, new { id = "formInvolved_project", onsubmit = "return validateCallback(this,dialogAjaxDone);" }))
        {
            @Html.Hidden("formOperateType")//表单操作类型：固定写法，只是保存，值为'onlySave';保存并且新增，值为'saveAndNewNext'
            @Html.Hidden("C_Involved_project_id", Model.C_Involved_project_id)
            @Html.Hidden("C_Involved_project_code", Model.C_Involved_project_code)
            @Html.Hidden("C_Involved_project_number", Model.C_Involved_project_number)
            @Html.Hidden("C_Involved_project_creator", Model.C_Involved_project_creator)
            @Html.Hidden("C_Involved_project_createTime", Model.C_Involved_project_createTime)
            @Html.Hidden("C_Involved_project_isDelete", Model.C_Involved_project_isDelete)
            <li><label>工程名称</label>@Html.TextBox("C_Involved_project_name", Model.C_Involved_project_name, new { @class = "dfinput", requiredInput = "请输入工程名称", maxlength = "200" })<i></i></li>
            <li><label>工程地点</label>@Html.TextBox("C_Involved_project_address", Model.C_Involved_project_address, new { @class = "dfinput", maxlength = "200" })<i></i></li>
            <li><label>工程类别</label>@Html.TextBox("C_Involved_project_type", Model.C_Involved_project_type, new { @class = "dfinput", maxlength = "100" })<i></i></li>
            <li><label>工程建设规模(㎡)</label>@Html.TextBox("C_Involved_project_scale", Model.C_Involved_project_scale, new { @class = "dfinput", money="请输入有效金额",maxlength = "100" })<i></i></li>
            <li><label>工程建设投资</label>@Html.TextBox("C_Involved_project_Investment", Model.C_Involved_project_Investment, new { @class = "dfinput",  money = "请输入有效金额", maxlength = "100" })<i></i></li>
           <li class="buttonWrap clear"><label>&nbsp;</label><input name="" type="button" id="btnSave" onclick="onlySaveForm(this)" class="btn btnmr fl" value="确认保存" /><i></i><input name="" id="btnSaveAndNewNext" type="button" onclick="saveAndNewNext(this)" class="btn btnmr fl" value="保存并新增下一个" /><i></i></li>
        }
    </ul>
</div>

Erp/Portal/Areas/BaseData/Views/Involved_project/List.cshtml
@using CommonService.Model.SysManager;
@using Context;
@using CommonService.Model;
@model IEnumerable<CommonService.Model.C_Involved_project>
@{
    Layout = "~/Views/Shared/_ListSearchWithDialogTemplate.cshtml";//带表单查询的列表页面固定模板
}
@{
    ViewBag.Title = "涉案项目列表";
}

@{
    C_Involved_project projectConditon = ViewBag.ProjectConditon;//案件条件模型
    List<C_Role_button> RoleButtons = ViewBag.RoleButtons;//按钮权限
}
<div class="tools">
    <ul class="toolbar" style="margin-bottom:8px">
        @if (UIContext.Current.IsPreSetManager)
        {
            <li><a target="popdialog" title="涉案项目信息" dialogwidth="600" dialogheight="400" href="/basedata/Involved_project/create"><span><img src="/theme/images/new_add.png" /></span>添加</a></li>
            <li><a target="popdialog" title="涉案项目信息" dialogwidth="600" dialogheight="400" edit="edit" href="/basedata/Involved_project/edit?Involved_project_code={sid_Iterm}"><span><img src="/theme/images/new_edit.png" /></span>修改</a></li>
            <li><a target="ajaxtodo" title="确认要删除选中数据吗?" singleoperate="singleoperate" href="/basedata/Involved_project/delete?Involved_project_code={sid_Iterm}"><span><img src="/theme/images/new_delete.png" /></span>删除</a></li>
            <li><a target="popdialog" title="涉案项目详细" dialogwidth="1240" dialogheight="550" edit="edit" href="/basedata/Involved_project/CutTabDetails?Involved_project_code={sid_Iterm}"><span><img src="/theme/images/new_view.png" /></span>详细</a></li>
            <li><a target="popdialog" title="建设单位" dialogwidth="1400" dialogheight="720" edit="edit" href="/basedata/Involved_project_CU/list?Involved_project_code={sid_Iterm}"><span></span>建设单位</a></li>
            <li><a target="popdialog" title="项目关联单位" dialogwidth="1600" dialogheight="720" edit="edit" href="/basedata/Involved_projectUnit/list?Involved_project_code={sid_Iterm}"><span></span>项目关联单位</a></li>
        }
        else
        {
            if (RoleButtons.Where(r => r.C_Menu_buttons_id == 12).Count() != 0)
            {
                <li><a target="popdialog" title="涉案项目信息" dialogwidth="800" dialogheight="550" href="/basedata/Involved_project/create"><span><img src="/theme/images/new_add.png" /></span>添加</a></li>
            }
            if (RoleButtons.Where(r => r.C_Menu_buttons_id == 13).Count() != 0)
            {
                <li><a target="popdialog" title="涉案项目信息" dialogwidth="800" dialogheight="550" edit="edit" href="/basedata/Involved_project/edit?Involved_project_code={sid_Iterm}"><span><img src="/theme/images/new_edit.png" /></span>修改</a></li>
            }
            if (RoleButtons.Where(r => r.C_Menu_buttons_id == 14).Count() != 0)
            {
                <li><a target="ajaxtodo" title="确认要删除选中数据吗?" singleoperate="singleoperate" href="/basedata/Involved_project/delete?Involved_project_code={sid_Iterm}"><span><img src="/theme/images/new_delete.png" /></span>删除</a></li>
            }
            if (RoleButtons.Where(r => r.C_Menu_buttons_id == 15).Count() != 0)
            {
                <li><a target="popdialog" title="涉案项目详细" dialogwidth="1240" dialogheight="550" edit="edit" href="/basedata/Involved_project/CutTabDetails?Involved_project_code={sid_Iterm}"><span></span>详细</a></li>
            }
            if (RoleButtons.Where(r => r.C_Menu_buttons_id == 16).Count() != 0)
            {
                <li><a target="popdialog" title="建设单位" dialogwidth="1400" dialogheight="720" edit="edit" href="/basedata/Involved_project_CU/list?Involved_project_code={sid_Iterm}"><span></span>建设单位</a></li>
            }
            if (RoleButtons.Where(r => r.C_Menu_buttons_id == 17).Count() != 0)
            {
                <li><a target="popdialog" title="项目关联单位" dialogwidth="1600" dialogheight="720" edit="edit" href="/basedata/Involved_projectUnit/list?Involved_project_code={sid_Iterm}"><span></span>项目关联单位</a></li>
            }
        }
    </ul>
    @using (Html.BeginForm("List", "Involved_project", FormMethod.Post, new { id = ViewBag.SearchFormID, onsubmit = "return clickSearch(this);" }))
    {
        <ul class="seachform">
            <input name="ThisPageIndex" class="ThisPageIndex" type="hidden" value="@ViewBag.ThisPageIndex" />
            <input name="IsExcutedFormSearch" class="IsExcutedFormSearch" type="hidden" value="@ViewBag.IsExcutedFormSearch" />
            <li><label>工程地点</label>@Html.TextBox("C_Involved_project_address", projectConditon.C_Involved_project_address, new { @class = "scinput" })</li>
            
            <li><label>涉案项目名称</label>@Html.TextBox("C_Involved_project_name", projectConditon.C_Involved_project_name, new { @class = "scinput" })</li>
            <li><label>工程类别</label>@Html.TextBox("C_Involved_project_type", projectConditon.C_Involved_project_type, new { @class = "scinput" })</li>
             <li><label>&nbsp;</label><input type="submit" class="scbtn" style="color:blue;" value="查询" /></li>
        </ul>
    }
</div>

<table class="tablelist">
    <thead>
        <tr>
            <th width="25%">工程名称</th>
            <th width="30%">工程地点</th>
            <th width="10%">工程类别</th>
            <th width="10%">工程建设规模</th>
            <th width="*%">工程建设投资</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr target="sid_Iterm" rel="@item.C_Involved_project_code" relname="@item.C_Involved_project_name" ondblclick="openDetailsView('15','项目详细','1240','550','/basedata/Involved_project/tabdetails?Involved_project_code=@item.C_Involved_project_code','@(UIContext.Current.IsPreSetManager==true ?  "1" : "0")','@ViewBag.RoleButtonIds')">
                <td>@item.C_Involved_project_name</td>
                <td>@item.C_Involved_project_address</td>
                <td>@item.C_Involved_project_type</td>
                <td>@item.C_Involved_project_scale</td>
                <td>@item.C_Involved_project_Investment</td>
            </tr>
        }
    </tbody>
</table>    

Erp/Portal/Areas/BaseData/Views/Involved_project/MulityCallbackRefList.cshtml
@using CommonService.Model;
@using Context;
@using CommonService.Model.SysManager;
@model IEnumerable<CommonService.Model.C_Involved_project>
@{
    Layout = "~/Views/Shared/_ListSearchWithCallbackTemplate.cshtml";//包含回调方法的列表页面固定模板
}
@{
    ViewBag.Title = "涉案项目列表";
}

@{
    C_Involved_project projectConditon = ViewBag.ProjectConditon;//案件条件模型
    List<C_Role_button> RoleButtons = ViewBag.RoleButtons;//按钮权限
}
@section HeadScript{
@*<script type="text/javascript" src="/theme/js/jquery-ui.js"></script>
  <script type="text/javascript" src="/theme/js/jquery.dialogextend.1_0_1.js"></script>
  <script type="text/javascript" src="/theme/js/alertDialog.js"></script>*@
    <script type="text/javascript">
        $(function () {

            $("#allChecked").click(function () {
                if (this.checked) {
                    $(".tablelist :checkbox").prop("checked", true);
                } else {
                    $(".tablelist :checkbox").prop("checked", false);
                }
            });
            $("table.tablelist tr").slice(1).each(function () {//slice(1)表示排除第一行
                var p = this;
                $(this).children().slice(1).click(function () {
                    $($(p).children()[0]).children().each(function () {//$(p).children()[0]表示第一列
                        if (this.type == "checkbox") {
                            if (!this.checked) this.checked = true;
                            else this.checked = false;
                        }
                    });
                });
            });
            $("a[target=popdialog_owndefine]").each(function () {
                $(this).click(function (event) {
                    event.preventDefault();
                    var $this = $(this);
                    //替换url参数
                    var switchUrl = $this.attr("href");
                    _openDialog($(this).attr("title"), switchUrl, $(this).attr("dialogwidth"), $(this).attr("dialogheight"));
                });
            });
        })
    </script>
<script type="text/javascript" src="/theme/js/basedialog.js"></script>

}
@section HeadCss{
    @*<link href="/theme/css/jquery-ui.css" rel="stylesheet" type="text/css" />*@
    <style type="text/css">
        .aaa:link {
            color: blue;
        }

        .aaa:hover {
            color: blue;
        }

        .aaa:visited {
            color: blue;
        }

        .forminfo {
        }
    </style>
}
<div class="callback_list_tool">
    <div class="tools">
        <ul class="toolbar">
            <li><a target="ajaxtodo" mulityoperate="mulityoperate" href="javascript:window.parent.mulityBringBack({callbackjson})"><span><img src="/theme/images/new_ok.png" /></span>确定</a></li>
        </ul>
        @using (Html.BeginForm("MulityCallbackRefList", "Involved_project", FormMethod.Post, new { id = ViewBag.SearchFormID, onsubmit = "return clickSearch(this);" }))
        {
            <ul class="seachform">
                <input name="ThisPageIndex" class="ThisPageIndex" type="hidden" value="@ViewBag.ThisPageIndex" />
                <input name="IsExcutedFormSearch" class="IsExcutedFormSearch" type="hidden" value="@ViewBag.IsExcutedFormSearch" />
                <li><label>涉案项目名称</label>@Html.TextBox("C_Involved_project_name", projectConditon.C_Involved_project_name, new { @class = "scinput" })</li>
                <li><label>&nbsp;</label><input type="submit" class="scbtn" value="查询" /></li>
            </ul>
        }
    </div>
</div>
    <table class="tablelist">
        <thead>
            @{
                string callbackStr2 = "";

                callbackStr2 = "{'mulitylookupgroup':'projectlookup','Code':'','Name':''}";
              
                
                
            }
            <tr callbackjson="@callbackStr2">
                <th><input id="allChecked" type="checkbox" mulitycheck="mulitycheck" value=""></th>
                <th>工程名称</th>
                <th>工程地点</th>
                <th>工程类别</th>
                <th>工程建设规模</th>
                <th>工程建设投资</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr target="sid_Iterm" rel="@item.C_Involved_project_code" callbackjson="{'mulitylookupgroup':'projectlookup','Code':'@item.C_Involved_project_code','Name':'@item.C_Involved_project_name'}">
                    @if (ViewBag.checkedProjectCode != null && ViewBag.checkedProjectCode.Contains(item.C_Involved_project_code.ToString()))
                    {
                        <td><input operate="operate" type="checkbox" checked="checked" value=""></td>
                    }else
                    {
                        <td><input operate="operate" type="checkbox" value=""></td>
                    }
                    @if (UIContext.Current.IsPreSetManager)
                    {
                        <td><a class="aaa" target="popdialog_owndefine" title="涉案项目详细" dialogwidth="1240" dialogheight="550" href="/basedata/Involved_project/tabdetails?Involved_project_code=@item.C_Involved_project_code">@item.C_Involved_project_name</a></td>
                    }else
                    {
                        if(RoleButtons.Where(r => r.C_Menu_buttons_id == 15).Count() != 0)
                        {
                            <td><a class="aaa" target="popdialog_owndefine" title="涉案项目详细" dialogwidth="1240" dialogheight="550" href="/basedata/Involved_project/tabdetails?Involved_project_code=@item.C_Involved_project_code">@item.C_Involved_project_name</a></td>
                        }else
                        {
                            <td><a class="aaa" href="#">@item.C_Involved_project_name</a></td>
                        }
                    }
                    <td>@item.C_Involved_project_address</td>
                    <td>@item.C_Involved_project_type</td>
                    <td>@item.C_Involved_project_scale</td>
                    <td>@item.C_Involved_project_Investment</td>
                </tr>
            }
        </tbody>
    </table>

Erp/Portal/Areas/BaseData/Views/Involved_project/SingleCallbackRefList.cshtml
@using CommonService.Model;
@model IEnumerable<CommonService.Model.C_Involved_project>
@{
    Layout = "~/Views/Shared/_ListSearchWithCallbackTemplate.cshtml";//包含回调方法的列表页面固定模板
}
@{
    ViewBag.Title = "涉案项目列表";
}

@{
    C_Involved_project projectConditon = ViewBag.ProjectConditon;//案件条件模型
}
<div class="callback_list_tool">
    <div class="tools">
        <ul class="toolbar">
            <li><a target="ajaxtodo" singleoperate="singleoperate" href="javascript:window.parent.bringBack({callbackjson})"><span><img src="/theme/images/new_ok.png" /></span>确定</a></li>
        </ul>
        @using (Html.BeginForm("SingleCallbackRefList", "Involved_project", FormMethod.Post, new { id = ViewBag.SearchFormID, onsubmit = "return clickSearch(this);" }))
        {
            <ul class="seachform">
                <input name="ThisPageIndex" class="ThisPageIndex" type="hidden" value="@ViewBag.ThisPageIndex" />
                <input name="IsExcutedFormSearch" class="IsExcutedFormSearch" type="hidden" value="@ViewBag.IsExcutedFormSearch" />
                <li><label>涉案项目名称</label>@Html.TextBox("C_Involved_project_name", projectConditon.C_Involved_project_name, new { @class = "scinput" })</li>
                <li><label>&nbsp;</label><input type="submit" class="scbtn" value="查询" /></li>
            </ul>
        }
    </div>
</div>
    <table class="tablelist">
        <thead>
            <tr>
                <th>工程名称</th>
                <th>工程地点</th>
                <th>工程类别</th>
                <th>工程建设规模</th>
                <th>工程建设投资</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr target="sid_Iterm" rel="@item.C_Involved_project_code" callbackjson="{'lookupgroup':'projectlookup','Code':'@item.C_Involved_project_code','Name':'@item.C_Involved_project_name'}">
                    <td>@item.C_Involved_project_name</td>
                    <td>@item.C_Involved_project_address</td>
                    <td>@item.C_Involved_project_type</td>
                    <td>@item.C_Involved_project_scale</td>
                    <td>@item.C_Involved_project_Investment</td>
                </tr>
            }
        </tbody>
    </table>